platform :ios, '8.0'
use_frameworks!

target 'Demo' do
    pod 'LoremIpsum'
    pod 'NoChat', :path => "../"
    pod 'NoChatTG', :path => "../"
    pod 'NoChatMM', :path => "../"
    pod 'NoChatSLK', :path => "../"
end

