platform :ios, '8.0'

target 'NoChat-Swift-Example' do
    use_frameworks!
    
    pod 'NoChat', :path => '../../'
    pod 'NOCProtoKit', :path => '../'
    pod 'YYText'
    pod 'HPGrowingTextView'

end
